# Generated by Django 3.0.5 on 2023-11-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_treatment_medical_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='medical_event',
        ),
        migrations.DeleteModel(
            name='MedicalEvent',
        ),
    ]
