# Generated by Django 3.0.5 on 2023-11-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20231125_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='treatmentDate',
        ),
    ]
