# Generated by Django 3.0.5 on 2023-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20231126_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatmentDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
